### PR TITLE
lv_canvas: add basic drawing functionalities

### PR DESCRIPTION
**Pull request by seyyah**
Related to https://github.com/littlevgl/lvgl/pull/758

### CODE REVIEW

**Comment by seyyah** [comment]
I couldn't compile pc_simulator with LittlevGL v5.3 so I didn't add the lv_test_canvas_2.png

**Comment by seyyah** [comment]
I want to use `lv_task` utilities but I couldn't.

**Comment by kisvegabor** [comment]
> I want to use lv_task utilities but I couldn't.

How do you mean it? Why couldn't you compile it?

**Comment by seyyah** [comment]
> > I want to use lv_task utilities but I couldn't.
> 
> How do you mean it? Why couldn't you compile it?

@kisvegabor I tried to make similar to obj_mem_leak_tester. But I got only empty canvas area.  Consecutive drawings did not make.

**Comment by kisvegabor** [comment]
Strange, you can open an issue to examine it.


`lv_canvas_fill_polygon` still not clear to me. If you comment out `lv_canvas_flood_fill` the `bg_color` parameter is not used.

https://github.com/littlevgl/lvgl/blob/dev-5.3/lv_objx/lv_canvas.c#L403-L418

**Comment by seyyah** [comment]
> Strange, you can open an issue to examine it.

We open an issue ASAP.

> lv_canvas_fill_polygon still not clear to me. If you comment out lv_canvas_flood_fill the bg_color parameter is not used.
> https://github.com/littlevgl/lvgl/blob/dev-5.3/lv_objx/lv_canvas.c#L403-L418

PR: lv_canvas: lv_canvas_boundary_fill4 function interface enhancement [#783](https://github.com/littlevgl/lvgl/pull/783)

**Comment by kisvegabor** [comment]
Thank you for both of the PRs!

**Pull request merged**
