### PR TITLE
update mode test for LV_CHART_TYPE_LINE

### PR DESCRIPTION
**Pull request by ali-rostami**
If this test is OK I can add a test for the other chart types in lv_test_chart_3 function. so what do think @kisvegabor ?

### CODE REVIEW

**Comment by kisvegabor** [comment]
It would be great! Please add tests for other chart types too.

**Comment by kisvegabor** [comment]
Not stale

**Comment by ali-rostami** [comment]
sorry for being late
I will work on it soon.

**Comment by ali-rostami** [comment]
dear @kisvegabor would please take look why it doesn't work with `LV_CHART_TYPE_AREA`. thanks.

**Comment by kisvegabor** [comment]
There a few bugs in `lv_chart_draw_areas`. Now it should work.

**Comment by ali-rostami** [comment]
thanks. yep, It's fine now.

**Comment by kisvegabor** [comment]
Great! I merged it.

**Pull request merged**
