### PR TITLE
Show switch animation in lv_test_theme

### PR DESCRIPTION
**Pull request by embeddedt**

### CODE REVIEW

**Comment by kisvegabor** [comment]
Than you!

**Comment by kisvegabor** [comment]
Upps, we forget something. `lv_sw_set_anim_time` is only in `dev-5.3` so it won't work with `lvgl` `master`.

I suggest to adding:
```c
#if LVGL_VERSION_MAJOR == 5 && LVGL_VERSION_MINOR >= 3
    lv_sw_set_anim_time(sw, 250);
#endif
```

**Comment by embeddedt** [comment]
@kisvegabor Thanks for catching that! Do you want another PR?

**Comment by kisvegabor** [comment]
I think it'd be better to reopen this one.

**Comment by embeddedt** [comment]
@kisvegabor A PR can't be reopened once it's merged.

**Comment by kisvegabor** [comment]
Oh, I see. Then just push the update please.

**Comment by embeddedt** [comment]
@kisvegabor As I'm not a member of the `littlevgl` organization on GitHub I only have push access to the main lvgl repository.

**Comment by kisvegabor** [comment]
Ok, I've pushed the fix.
Would you like to be a Collaborator here too? It would make easier to handle situations like this.

**Comment by embeddedt** [comment]
@kisvegabor Yes please, and thank you!

**Comment by embeddedt** [comment]
@kisvegabor I just realized that your `ifdef` will need to be adjusted when `v6.0` is released, because it currently requires the major version to be 5.

**Comment by kisvegabor** [comment]
@embeddedt I've sent the invitation.
I thought we can just remove the `#ifdef` when `v5.3` will be released. As `v6.0` can contain API changes we can't be sure that any of the current functions will work.

**Comment by embeddedt** [comment]
@kisvegabor Thanks! Good point.

**Pull request merged**
